package tcss543;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;

import Utility.Utils;
import algorithms.FordFulkerson;
import algorithms.PreflowPush;
import algorithms.ScalingFordFulkerson;
import graph.GraphInput;
import graph.SimpleGraph;


/**
 * This class is used to test the performance of three algorithms
 * on a range of graphs of each type.
 * @author yanan
 * @version Dec.2016
 *
 */
public class PerformanceTest {
	
	public static Utils ut;


	public static void main(String[] args) {
		// TODO Auto-generated method stub
		  SimpleGraph simpleG;
          simpleG= new SimpleGraph();
        
        	  GraphInput.LoadSimpleGraph(simpleG, args[0]);
        	  System.out.print(performanceTesting());
        
	}
	
	
	/**
	 * use the graphs generated by {@link graphGenerator.java} to 
	 * test the performance of each algorithm
	 * @return
	 */
	public static String performanceTesting (){
		
		return null;
	}
	

}
